.\" Copyright (c) 2015 Fabio Castelli

.TH TEXTDATAPARSER "1" "November 22, 2015"

.SH NAME
.B TextDataParser
\- View text data files with definitions.

.SH SYNOPSIS
.B textdataparser
[options]

.SH DESCRIPTION
.PP
.B TextDataParser
is a A GTK+ utility to view text data files with a definitions file.

.SH REPORTING BUGS
Report bugs to https://github.com/muflone/textdataparser/issues

.SH AUTHORS
.B TextDataParser
was written by Fabio Castelli (Muflone) <muflone@vbsimple.net>

.SH HOMEPAGE
Home page: http://www.muflone.com/textdataparser/

Source code: https://github.com/muflone/textdataparser/

.SH COPYRIGHT
Copyright © 2015 Fabio Castelli.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/gpl-2.0.html>.

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
